baseURL: "https://tchelinux.org/"
languageCode: "pt-br"
title: "Tchelinux"
theme: "tchelinux"
googleAnalytics: "UA-123456789-1"

menu:
  nav:
    - pre: fa-home
      url: /
      weight: 1

    - name: Sobre o Tchelinux
      url: https://wiki.tchelinux.org/#!sobre.md
      weight: 2

    - name: Onde estamos?
      url: https://wiki.tchelinux.org/#!onde.md
      weight: 3

    - name: Como participar?
      url: https://wiki.tchelinux.org/#!como_participar.md
      weight: 4

    - name: Como ajudar?
      url: https://wiki.tchelinux.org/#!como_ajudar.md
      weight: 5

    - name: Calendário de Eventos
      url: https://wiki.tchelinux.org/#!eventos/calendario.md
      weight: 6

    - name: Certificados
      url: https://certificados.tchelinux.org/
      weight: 7

    - name: Wiki
      url: https://wiki.tchelinux.org/
      weight: 8

    - name: 🇺🇸
      url: /en
      weight: 9

params:
  hero: Tchelinux, Software Livre em Ação!
  desc: -|
    A paixão pelo Software Livre assim como o desejo de compartilhar conhecimentos fez com que um grupo de usuários se reunisse e trabalhasse junto na organização de eventos para a divulgação de ferramentas e da filosofia open source em instituições educacionais do Rio Grande do Sul. Aproveitando a ideia de voluntariado, o grupo decidiu que os eventos seriam sempre gratuitos, porém os participantes são encorajados a doar 2kg de alimentos não-perecíveis, que são encaminhados a instituições de caridade da cidade onde ocorre o evento.
    Desde Outubro de 2006 o Tchelinux realizou 103 eventos em 22 com o auxílio de milhares de voluntários, que ajudaram na organização e apresentando 1658 palestras foram assistidas por 12934 participantes que doaram 18589 kg de alimentos para 55 instituições de caridade.
    Há muito trabalho a ser feito e todos são bem-vindos a participar do Tchelinux e ajudar a divulgar o Software Livre e levar o conhecimento à todos cantos do Sul do Brasil!
    Contamos com você!
