[build]
publish = "public"
command = "hugo --gc --minify -b $URL"

[build.environment]
HUGO_VERSION = "0.62.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
